# Generated by Django 4.2.16 on 2024-10-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birthday", "0002_alter_birthday_birthday"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="birthday",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "birthday"),
                name="Unique person constraint",
            ),
        ),
    ]
