# Generated by Django 4.2.16 on 2024-10-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("birthday", "0003_birthday_unique_person_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="birthday",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="birthday_images", verbose_name="Фото"
            ),
        ),
    ]
